# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='One',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=60)),
                ('integ', models.IntegerField(default=0)),
                ('boole', models.BooleanField(default=False)),
            ],
        ),
    ]
